# Generated by Django 2.2.1 on 2019-05-28 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100)),
                ('purchase_channel', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('delivery_service', models.CharField(max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('line_items', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('production', 'production'), ('closing', 'closing'), ('sent', 'sent')], default='ready', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100)),
                ('purchase_channel', models.CharField(max_length=100)),
                ('orders', models.ManyToManyField(to='api.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
